name: Bump version
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Fetches entire history, so we can analyze commits since last tag
          fetch-depth: 0
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v4.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Docker Image to GPR
        uses: machine-learning-apps/gpr-docker-publish@master
        id: docker
        with:
          IMAGE_NAME: 'mongo-backup-s3'
          TAG: ${{ steps.tag_version.outputs.new_tag }}
          DOCKERFILE_PATH: 'Dockerfile'
          BUILD_CONTEXT: '.'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.tag_version.outputs.new_tag }}
      - name: docker results
        run: |
          echo "The name:tag of the Docker Image is: $VAR1"
          echo "The docker image is hosted at $VAR2"
        env:
          VAR1: ${{ steps.docker.outputs.IMAGE_SHA_NAME }}
          VAR2: ${{ steps.docker.outputs.IMAGE_URL }}
